# Generated by Django 4.1.5 on 2023-01-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='history',
            field=models.TextField(blank=True),
        ),
    ]
