# Generated by Django 4.1.5 on 2023-02-08 07:16

import device_api.file_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_api', '0005_remove_device_history_historicalemployee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=device_api.file_storage.upload_remote_path)),
            ],
        ),
    ]
